/* 导出：LTspice 小信号平均模型（.ac 环路测量）、PSIM 参数文件、JSON
   网表注释用英文，避免旧版 LTspice 的编码问题。 */
(function (G) {
'use strict';
const PS = G.PS;
const n = v => Number((+v).toPrecision(6)).toString();
PS.spn = n;

// 模拟补偿网络（运放或 OTA），用圆整后的元件值。ac=true 时参考接地（小信号）
PS.compNet = function (R, inNode, outNode, ac, tag) {
  const P = R.P, g = k => { const x = R.rz.parts.find(p => p.name === k); return x ? n(x.val) : null; }, t = R.rz.cpReal.type, L = [];
  tag = tag || '';
  if (P.family === 'ota') {
    L.push(`Rt${tag} ${inNode} fbd${tag} ${g('Rt')}`, `Rb${tag} fbd${tag} 0 ${g('Rb')}`);
    if (g('Cff')) L.push(`Cff${tag} ${inNode} fbd${tag} ${g('Cff')}`);
    if (ac) L.push(`Gota${tag} ${outNode} 0 fbd${tag} 0 ${n(P.gm)}`);
    else L.push(`Bota${tag} 0 ${outNode} I=${n(P.gm)}*limit(V(ref)-V(fbd${tag}),-0.2,0.2)`, `Rleak${tag} ${outNode} 0 1e9`);
    if (t === 1) L.push(`Cc${tag} ${outNode} 0 ${g('Cc')}`);
    else L.push(`Rc${tag} ${outNode} cz${tag} ${g('Rc')}`, `Cc${tag} cz${tag} 0 ${g('Cc')}`, `Cp${tag} ${outNode} 0 ${g('Cp')}`);
  } else {
    L.push(`R1${tag} ${inNode} inv${tag} ${g('R1')}`);
    if (g('Rb')) L.push(`Rb${tag} inv${tag} 0 ${g('Rb')}`);
    if (t === 1) L.push(`C1${tag} inv${tag} ${outNode} ${g('C1')}`);
    else L.push(`R2${tag} inv${tag} m${tag} ${g('R2')}`, `C1${tag} m${tag} ${outNode} ${g('C1')}`, `C2${tag} inv${tag} ${outNode} ${g('C2')}`);
    if (t === 3) L.push(`R3${tag} ${inNode} m3${tag} ${g('R3')}`, `C3${tag} m3${tag} inv${tag} ${g('C3')}`);
    if (ac) L.push(`Eea${tag} ${outNode} 0 0 inv${tag} 1e6`);
    else L.push(`Bea${tag} ${outNode} 0 V=limit(1e5*(V(${tag === 'i' ? '0' : 'ref'})-V(inv${tag})),0,${n(P.Vcmax)})`);
  }
  return L;
};
// z 域多项式 → LTspice Laplace 表达式（z^-1 = ρ·e^{-sT}，ρ 略小于 1 使直流有限）
PS.zLaplace = function (dc, T) {
  const term = (c, i) => i === 0 ? n(c) : `${n(c)}*exp(-s*${n(i * T)})*${n(Math.pow(0.99999, i))}`;
  return `(${dc.b.map(term).join('+')})/(${dc.a.map(term).join('+')})`.replace(/\+-/g, '-');
};

PS.netAvg = function (R) {
  const P = R.P, op = R.op, ctx = R.ctx, dg = ctx.dig, dig = P.impl === 'digital', L = [];
  L.push(`* ${PS.TOPOS[P.topo]} ${P.mode.toUpperCase()} ${P.impl} -- small-signal averaged model (LTspice)`);
  L.push(`* Linearized at Vin=${n(P.Vin)} V, Io=${n(P.Io)} A, D=${op.D.toFixed(4)}; all node voltages are AC perturbations.`);
  L.push('* Loop gain T = -V(vo)/V(fb)   (plot it; PM = 180 + phase at |T| = 1)');
  L.push('* Generated by Loop Compensation Design Tool');
  if (P.mode === 'cotr') {
    const rcC = P.Rc * P.C, b = rcC - op.Ton / 2, k = op.Ton * op.Ton / (Math.PI * Math.PI);
    L.push('* Ripple-based COT: behavioral plant vo/vc (Jian Li model), stability needs rc*C > Ton/2');
    L.push(`Ecr vo 0 vc 0 Laplace=${n(1 / ctx.H)}*(1+s*${n(rcC)})/(1+s*${n(b)}+s*s*${n(k)})`);
  } else {
    L.push('* --- power stage ---');
    L.push(`Bsw sw 0 V=${n(op.a)}*V(d)+${n(1 - op.bv)}*V(vo)`);
    L.push(`L1 sw x ${n(P.L)}`, `Rs x y ${n(op.Rs)}`, 'Evl y 0 vo 0 1');
    L.push(`Bo 0 vo I=${n(op.bi)}*I(Evl)-${n(op.b2)}*V(d)`);
    L.push(`Resr vo c1 ${n(P.Rc)}`, `Cout c1 0 ${n(P.C)}`, `Rload vo 0 ${n(op.R)}`);
    L.push('Bil il 0 V=I(Evl)');
  }
  L.push('* --- loop injection (Middlebrook) ---', 'Vinj fb vo AC 1');
  L.push('* --- compensator ---');
  if (R.noLoop) L.push('Rvc vc 0 1  ; no error amplifier: vc fixed (AC ground)', '* (loop gain undefined; plot V(vo)/V(vc) instead)');
  else if (dig) L.push(`Ecd vc 0 fb 0 Laplace=${n(-R.kin)}*${PS.zLaplace(R.qz, ctx.Ts)}`);
  else PS.compNet(R, 'fb', 'vc', true).forEach(x => L.push(x));
  L.push('* --- modulator ---');
  const He = () => {   // Ridley 二阶近似 He(s) ≈ 1 + s/(wn·Qz) + s²/wn²，Qz=−2/π，wn=π/Ts；再加远处双极点使其为真分式
    const wn = Math.PI / op.Ts, k1 = -Math.PI / 2 / wn, k2 = 1 / (wn * wn), wp = 10 * wn;
    return `Ehe ihe 0 il 0 Laplace=(1+s*${n(k1)}+s*s*${n(k2)})/((1+s/${n(wp)})*(1+s/${n(wp)}))`;
  };
  if (P.mode === 'vmc') L.push(dig ? `Ed d 0 vc 0 Laplace=exp(-s*${n(dg.Td)})/${n(dg.Npwm)}` : `Bd d 0 V=V(vc)/${n(P.Vm)}`);
  else if (P.mode === 'pcmc') {
    const Fm = PS.Fm(op, ctx.Se);
    L.push(He());
    if (dig) L.push(`Edl vcd 0 vc 0 Laplace=exp(-s*${n(dg.Td)})`, `Bd d 0 V=${n(Fm)}*(${n(dg.Kdac)}*V(vcd)-${n(P.Ri)}*V(ihe))`);
    else L.push(`Bd d 0 V=${n(Fm)}*(V(vc)-${n(P.Ri)}*V(ihe))`);
  } else if (P.mode === 'acm') {
    if (dig) {
      L.push(`Bei ei 0 V=V(vc)-${n(dg.Kadc * P.Ri)}*V(il)`, `Ed d 0 ei 0 Laplace=exp(-s*${n(dg.Td)})/${n(dg.Npwm)}*${PS.zLaplace(R.inner.qz, ctx.Ts)}`);
    } else {
      const Ri = R.inner.rz;
      L.push(`Bdi di 0 V=${n(P.Ri)}*V(il)-V(vc)`);
      PS.compNet({ P: Object.assign({}, P, { family: 'opamp' }), rz: Ri }, 'di', 'vca', true, 'i').forEach(x => L.push(x));
      L.push(`Bd d 0 V=V(vca)/${n(P.Vm)}`);
    }
  } else if (P.mode === 'coti') {
    L.push('* current-mode COT: iL forced to Hcot(s)*vc/Ri by a high-gain duty driver (Jian Li model)');
    L.push(`Ecot icmd 0 vc 0 Laplace=1/(1+s*${n(op.Ton / 2)}+s*s*${n(op.Ton * op.Ton / (Math.PI * Math.PI))})`);
    L.push(`Bd d 0 V=1e4*(V(icmd)-${n(P.Ri)}*V(il))`);
  }
  L.push('* --- analysis ---');
  L.push(`.ac dec 100 ${n(R.fmin)} ${n(R.fmax)}`);
  if (!R.noLoop) {
    L.push('.meas AC fc WHEN mag(-V(vo)/V(fb))=1 FALL=LAST');
    L.push('.meas AC Tfc FIND -V(vo)/V(fb) AT fc   ; log shows (0dB, phase); PM = 180 + phase');
  }
  L.push('.end');
  return L.join('\n') + '\n';
};

// PSIM：参数文件（name = value）+ s/z 域传递函数系数
PS.psim = function (R) {
  const P = R.P, op = R.op, L = [], ln = (k, v, c) => L.push(k + ' = ' + n(v) + (c ? '    // ' + c : ''));
  L.push('// PSIM parameter file -- ' + PS.TOPOS[P.topo] + ' ' + PS.MODES[P.mode] + ' (' + P.impl + ')');
  L.push('// 在 PSIM 中：Simulate → Parameter File 引用本文件，元件参数直接填变量名');
  ln('Vin', P.Vin, '输入电压 V'); ln('Vo', P.Vo, '输出电压 V'); ln('Io', P.Io, '负载电流 A'); ln('Rload', op.R, 'Ω');
  ln('fsw', P.fs, '开关频率 Hz'); ln('Lout', P.L, 'H'); ln('RL', P.RL, '电感 DCR'); ln('Cout', P.C, 'F'); ln('Resr', P.Rc, 'ESR');
  ln('Ron', P.Ron, 'MOSFET Rds(on)'); ln('Vref', P.Vref, '参考电压'); ln('Dnom', op.D, '标称占空比');
  if (P.mode === 'vmc' && P.impl === 'analog') ln('Vramp', P.Vm, '锯齿波峰峰值');
  if (P.mode !== 'vmc') ln('Ri', P.Ri, '电流采样增益 V/A');
  if (P.mode === 'pcmc') ln('Se', R.ctx.Se, '斜坡补偿斜率 V/s');
  if (P.mode === 'coti' || P.mode === 'cotr') ln('Ton', op.Ton, '导通时间 s');
  if (R.rz) R.rz.parts.forEach(p => ln(p.name, p.val, '补偿器元件（已圆整）'));
  if (R.inner && R.inner.rz) R.inner.rz.parts.forEach(p => ln(p.name + '_i', p.val, '电流内环补偿器元件'));
  const sPoly = cp => {   // Gc(s) = wi·Π(1+s/z) / (s·Π(1+s/p))，降幂系数
    const mul = (a, b) => { const r = new Array(a.length + b.length - 1).fill(0); a.forEach((x, i) => b.forEach((y, j) => { r[i + j] += x * y; })); return r; };
    let num = [cp.wi], den = [1, 0];
    cp.z.forEach(w => { num = mul(num, [1 / w, 1]); }); cp.p.forEach(w => { den = mul(den, [1 / w, 1]); });
    return { num, den };
  };
  if (R.rz) {
    const sp = sPoly(R.rz.cpReal);
    L.push('', '// 外环补偿器 s 域传递函数 Gc(s) = vc/(−vo)（PSIM "s-domain Transfer Function" 块，降幂排列）');
    L.push('// 分子: ' + sp.num.map(n).join(', '), '// 分母: ' + sp.den.map(n).join(', '));
  }
  if (R.qz) {
    L.push('', '// 数字补偿器 z 域传递函数（PSIM "z-domain Transfer Function" 块，fs = ' + n(P.fs) + ' Hz，降幂 z^0, z^-1 …）');
    L.push('// 输入：参考码 − ADC 码；输出：' + (P.mode === 'vmc' ? 'PWM 比较值（计数）' : P.mode === 'pcmc' ? 'DAC 码' : '电流参考码'));
    L.push('// b: ' + R.qz.b.map(n).join(', '), '// a: ' + R.qz.a.map(n).join(', '));
    ln('Kadc', R.ctx.dig.Kadc, 'ADC 码/V'); ln('Npwm', R.ctx.dig.Npwm, 'PWM 周期计数');
    if (R.inner && R.inner.qz) L.push('// 内环 b: ' + R.inner.qz.b.map(n).join(', '), '// 内环 a: ' + R.inner.qz.a.map(n).join(', '));
  }
  return L.join('\n') + '\n';
};

})(typeof window !== 'undefined' ? window : globalThis);
