/* LTspice 开关级瞬态网表：理想开关功率级 + 行为级控制器（全部控制模式，含数字差分方程）
   数字控制：采样保持链（开关+电容）按相序依次移位/采样/计算，周期起点装载（影子寄存器）。 */
(function (G) {
'use strict';
const PS = G.PS, n = v => Number((+v).toPrecision(6)).toString();

PS.netSw = function (R) {
  const P = R.P, op = R.op, ctx = R.ctx, dg = ctx.dig, dig = P.impl === 'digital', mode = P.mode, Ts = 1 / P.fs, L = [];
  const fc = R.mg && isFinite(R.mg.fc) ? R.mg.fc : P.fs / 20;
  const tss = PS.clamp(5 / fc, 60 * Ts, 4e-3), t1 = tss + Math.max(10 / fc, 150 * Ts), w = Math.max(8 / fc, 120 * Ts), t2 = t1 + w, tstop = t2 + w;
  const I1 = P.Io * P.stepFrom, dI = P.Io * (P.stepTo - P.stepFrom), Rl = P.Vo / Math.max(I1, P.Io * 0.01), H = ctx.H, vcl = 'limit(V(vc),0,' + n(P.Vcmax) + ')';
  L.push(`* ${PS.TOPOS[P.topo]} ${mode.toUpperCase()} ${P.impl} -- switching transient model (LTspice)`);
  L.push(`* Load step ${n(I1)} A -> ${n(I1 + dI)} A at ${n(t1)} s, back at ${n(t2)} s. Sensed output = V(vs).`);
  L.push('* Ideal switches + behavioral controller. Soft-start ramp on V(ref). Generated by Loop Compensation Design Tool');
  L.push(`.model SWP SW(Ron=${n(P.Ron)} Roff=1Meg Vt=0.5 Vh=-0.2)`);
  L.push('.model DB D(Ron=10m Roff=10Meg Vfwd=0.6)  ; MOSFET body diode, keeps an inductor current path during switch transitions');
  L.push('Vin vin 0 ' + n(P.Vin));
  if (P.topo === 'buck') L.push('S1 vin sw g 0 SWP', 'S2 sw 0 gn 0 SWP', 'D1 sw vin DB', 'D2 0 sw DB', `L1 sw vo ${n(P.L)} Rser=${n(P.RL)}`, 'Evs vs 0 vo 0 1');
  else if (P.topo === 'boost') L.push(`L1 vin sw ${n(P.L)} Rser=${n(P.RL)}`, 'S1 sw 0 g 0 SWP', 'S2 sw vo gn 0 SWP', 'D1 0 sw DB', 'D2 sw vo DB', 'Evs vs 0 vo 0 1');
  else L.push('S1 vin sw g 0 SWP', `L1 sw 0 ${n(P.L)} Rser=${n(P.RL)}`, 'S2 sw vo gn 0 SWP', 'D1 sw vin DB', 'D2 vo sw DB', 'Evs vs 0 0 vo 1  ; buck-boost output is negative, sense |Vo|');
  L.push(`Cout vo 0 ${n(P.C)} Rser=${n(P.Rc)}`, `Rload vo 0 ${n(Rl)}`);
  const step = `PULSE(0 ${n(dI)} ${n(t1)} 200n 200n ${n(t2 - t1)} 1 1)`;
  L.push(P.topo === 'buckboost' ? 'Iload 0 vo ' + step : 'Iload vo 0 ' + step);
  L.push(`Bisn isn 0 V=${n(P.Ri)}*I(L1)`, 'Bgn gn 0 V=1-V(g)');
  L.push(`Vref ref 0 PWL(0 0 ${n(tss)} ${n(P.Vref)})`);
  L.push(`Vph ph 0 PULSE(0 1 0 ${n(0.999 * Ts)} ${n(0.001 * Ts)} 0 ${n(Ts)})  ; period phase 0->1`);
  L.push(`Vclk clk 0 PULSE(0 1 0 1n 1n 20n ${n(Ts)})`);
  // SR 锁存器（复位优先）：电流源对 1 pF 充放电，二极管钳位到 0/1 V，无输入时弱再生保持；
  // 窄复位脉冲也能可靠翻转，不会停在中间电平
  const latch = (set, rst) => {
    L.push(`Bset set 0 V=${set}`, `Brst rst 0 V=${rst}`, 'Vone one 0 1', '.model DI D(Ron=1 Roff=1G Vfwd=0)',
      'Bq 0 qd I=if(V(rst)>0.5,-1m,if(V(set)>0.5,1m,if(V(qd)>0.5,1u,-1u)))', 'Cq qd 0 1p', 'Dq1 qd one DI', 'Dq2 0 qd DI',
      'Bg g 0 V=if(V(qd)>0.5,1,0)');
  };
  const dmax = `V(ph)>${n(P.Dmax)}`;
  // 模拟补偿器
  if (!dig && !R.noLoop) PS.compNet(R, 'vs', 'vc', false).forEach(x => L.push(x));
  if (R.noLoop) L.push('Evc vc 0 ref 0 1  ; no error amplifier: comparator threshold = Vref');

  if (!dig) {
    if (mode === 'vmc') latch('V(clk)', `if(${n(P.Vm)}*V(ph)>${vcl} | ${dmax},1,0)`);
    else if (mode === 'pcmc') latch('V(clk)', `if(V(isn)+${n(ctx.Se * Ts)}*V(ph)>${vcl} | ${dmax},1,0)`);
    else if (mode === 'acm') {
      L.push(`Bdi di 0 V=V(isn)-${vcl}`);
      PS.compNet({ P: Object.assign({}, P, { family: 'opamp' }), rz: R.inner.rz }, 'di', 'vca', false, 'i').forEach(x => L.push(x));
      latch('V(clk)', `if(${n(P.Vm)}*V(ph)>V(vca) | ${dmax},1,0)`);
    } else {
      const Toffmin = Math.min(0.12 * Ts, 250e-9);
      L.push('Bton ton 0 V=idt(V(g),0,V(g)<0.5)  ; on-time timer', 'Btoff toff 0 V=idt(1-V(g),0,V(g)>0.5)');
      const cmpOn = mode === 'coti' ? `V(isn)<${vcl}` : `${n(H)}*V(vs)<${vcl}`;
      latch(`if(${cmpOn} & V(toff)>${n(Toffmin)},1,0)`, `if(V(ton)>${n(op.Ton)},1,0)`);
    }
  } else {
    // 采样保持 τ = 300Ω·1pF = 0.3 ns，脉宽 8 ns；用 Gear 积分避免梯形法在刚性 RC 上振铃导致保持值出错
    L.push('.model SWSH SW(Ron=300 Roff=1e12 Vt=0.5 Vh=-0.1)', '.options method=gear');
    let ph = 0;
    // 采样时刻：PWM 周期起点前 tc（tc = Ts 时即本周期起点），各相间隔 20 ns
    const tS0 = ((1 - P.tcRatio) % 1 + 1) % 1 * Ts + 2e-9;
    const sh = (name, expr, k) => {      // 采样保持：第 k 相脉冲时把 expr 写入 V(name)
      L.push(`Vp${name} p${name} 0 PULSE(0 1 ${n(tS0 + k * 20e-9)} 1n 1n 8n ${n(Ts)})`, `Bi${name} i${name} 0 V=${expr}`, `S${name} i${name} c${name} p${name} 0 SWSH`, `C${name} c${name} 0 1p`, `E${name} ${name} 0 c${name} 0 1`);
    };
    const chain = (tag, qz, errExpr, umin, umax) => {   // 差分方程 u = Σb·e − Σa·u（a、b 为量化后系数）
      const N = qz.a.length - 1;
      for (let k = N; k >= 1; k--) { sh(`e${k}${tag}`, `V(e${k - 1}${tag})`, ph); sh(`u${k}${tag}`, `V(u${k - 1}${tag})`, ph); ph++; }   // 先移位（旧→更旧）
      sh(`e0${tag}`, errExpr, ph++);
      const sum = qz.b.map((b, i) => `${n(b)}*V(e${i}${tag})`).concat(qz.a.slice(1).map((a, i) => `${n(-a)}*V(u${i + 1}${tag})`)).join('+').replace(/\+-/g, '-');
      sh(`u0${tag}`, `limit(${sum},${n(umin)},${n(umax)})`, ph++);
    };
    const ini = PS.digInit(R), errV = `round(${n(dg.Kadc)}*V(ref))-round(${n(dg.Kadc * H)}*V(vs))`;
    chain('v', R.qz, errV, ini.umin, ini.umax);
    if (mode === 'acm') chain('i', R.inner.qz, `round(V(u0v))-round(${n(dg.Kadc)}*V(isn))`, ini.uimin, ini.uimax);
    // 周期起点装载
    const src = mode === 'acm' ? 'u0i' : 'u0v';
    L.push(`Vpld pld 0 PULSE(0 1 0 0.5n 0.5n 4n ${n(Ts)})`, `Bild ild 0 V=round(V(${src}))`, 'Sld ild cld pld 0 SWSH', 'Cld cld 0 1p', 'Ecmp cmp 0 cld 0 1');
    if (mode === 'pcmc') latch('V(clk)', `if(V(isn)+${n(ctx.Se * Ts)}*V(ph)>${n(dg.Kdac)}*V(cmp) | ${dmax},1,0)`);
    else latch('V(clk)', `if(${n(dg.Npwm)}*V(ph)>V(cmp) | ${dmax},1,0)`);
    L.push('Evc vc 0 cmp 0 1  ; controller output (counts)');
  }
  if (dig) {
    // 数字控制：从稳态起步（电感/电容/控制器历史预置），避免积分器从零爬升的长尾，与工具内仿真同口径
    const ini = PS.digInit(R), u0 = ini.u0, ic = [];
    ic.push(`V(vo)=${n(P.topo === 'buckboost' ? -P.Vo : P.Vo)}`, `I(L1)=${n(op.IL - op.dIL / 2)}`);
    L.filter(l => /^Cu\dv /.test(l)).forEach(l => ic.push(`V(c${l.split(' ')[0].slice(1)})=${n(u0)}`));
    if (mode === 'acm') L.filter(l => /^Cu\di /.test(l)).forEach(l => ic.push(`V(c${l.split(' ')[0].slice(1)})=${n(ini.ui0)}`));
    ic.push(`V(cld)=${n(mode === 'acm' ? ini.ui0 : ini.u0)}`);
    L.push('.ic ' + ic.join(' '));
    const k = L.findIndex(l => l.startsWith('Vref '));
    L[k] = `Vref ref 0 ${n(P.Vref)}  ; digital: start from steady state, no soft-start`;
  }
  L.push(`.tran 0 ${n(tstop)} 0 ${n(Ts / 200)} uic`);
  L.push(`.meas TRAN Vpre AVG V(vs) FROM ${n(t1 - 0.5 * w)} TO ${n(t1)}`);
  L.push(`.meas TRAN Vmin MIN V(vs) FROM ${n(t1)} TO ${n(t2)}`);
  L.push(`.meas TRAN Vmax MAX V(vs) FROM ${n(t2)} TO ${n(tstop)}`);
  L.push(`.meas TRAN Vend AVG V(vs) FROM ${n(t2 - 0.3 * w)} TO ${n(t2)}`);
  L.push('.options plotwinsize=0', '.end');
  return L.join('\n') + '\n';
};

})(typeof window !== 'undefined' ? window : globalThis);
